version: 2.1
orbs:
  # Your orb will be automatically injected here during the pipeline.
  # Reference your orb's jobs and commands below as they will exist when built.
  orb-tools: circleci/orb-tools@12.1
  # The orb definition is intentionally not included here. It will be injected into the pipeline.
  cloudsmith-npm: {}

# Use this tag to ensure test jobs always run,
# even though the downstream publish job will only run on release tags.
filters: &filters
  tags:
    only: /.*/

# Filter for release tags.
release-filters: &release-filters
  branches:
    ignore: /.*/
  tags:
    only: /^v[0-9]+\.[0-9]+\.[0-9]+$/

jobs:

  test-create_npmrc:
    docker:
      - image: cimg/node:20.12
    resource_class: small
    steps:
      - checkout
      - cloudsmith-npm/create_npmrc:
          repository: "circleci-orb-testing"
      - run:
          name: Assert environment variables have been set
          command: |
            if [ $CLOUDSMITH_DOWNLOADS_DOMAIN != "packages.ft.com" ]
            then
              echo "Test failed: CLOUDSMITH_DOWNLOADS_DOMAIN has not been set correctly."
              exit 1
            fi
            echo "All tests passed."

  test-npm_install_package_example:
    docker:
      - image: cimg/node:20.12
    steps:
      - checkout
      - cloudsmith-npm/create_npmrc:
          repository: "circleci-orb-testing"
      - run: npm install simple-npm-package==1.0.0

workflows:
  test-deploy:
    jobs:
      # Make sure to include "filters: *filters" in every test job you want to run as part of your deployment.
      # Test your orb's commands in a custom job and test your orb's jobs directly as a part of this workflow.
      - test-create_npmrc:
          context: circleci-orb-publishing
          filters: *filters
      - test-npm_install_package_example:
          context: circleci-orb-publishing
          filters: *filters
      # The orb must be re-packed for publishing, and saved to the workspace.
      - orb-tools/pack:
          filters: *release-filters
      - orb-tools/publish:
          orb_name: ft-circleci-orbs/cloudsmith-npm
          vcs_type: << pipeline.project.type >>
          pub_type: production
          # Ensure this job requires all test jobs and the pack job.
          requires:
            - orb-tools/pack
            - test-create_npmrc
            - test-npm_install_package_example
          # Use a context to hold your publishing token.
          context: circleci-orb-publishing
          filters: *release-filters
