description: >
  Authenticate with Cloudsmith and configure npm to use Cloudsmith.
parameters:
  repository:
    description: The identity/slug of the Cloudsmith repository
    type: string

usage:
  version: 2.1
  orbs:
    cloudsmith-npm: ft-circleci-orbs/cloudsmith-npm@1.1
  jobs:
    build:
      docker:
        - image: cimg/node:20.12
      steps:
        - checkout
        - cloudsmith-npm/configure_npm:
            repository: "your-repository-id"
        - run:
            name: Install packages from Cloudsmith
            command: npm install
  workflows:
    main:
      jobs:
        - build
